version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
  nginx:
    build: ./nginx
    ports:
     - "9000:80"
  mysql:
    image: mysql:5.7
    #挂载的卷需要根据本机情况更改
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: aaa
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456